[sources.kafka]
  type = "kafka"
  bootstrap_servers = "kafka:29092"
  group_id = "vector"
  topics = ["chair1.bigmachine"]


[transforms.bigmachine]
  type = "remap"
  inputs = ["kafka"]
  source = """
    . = parse_json!(.message)
  """


[sinks.influxdb]
  type = "influxdb_logs"
  inputs = ["bigmachine"]
  endpoint = "http://influxdb:8086"
  org = "fcd228baaecf145a"
  bucket = "chair1.bigmachine"
  measurement = "values"
  token = "QKKxpKuRU1bwT7Zdh6hOjAR1V-ZS0n0xXaxkr_KslPYsp2DTbiRcqsUtWEjZzru9RGUYbSpB5oOXlZp7Bke9nA=="
