[http]
  bind-address = ":8888"

[[servers]]
  name = "InfluxDB"
  url = "http://influxdb:8086"
  default = true

[templates]
  [templates.my_template]
    name = "My Custom Dashboard"
    url = "https://raw.githubusercontent.com/influxdata/community-templates/master/chronograf/dashboard/github-overview.yml"
    description = "This is a custom dashboard for GitHub overview."

[tags]

